#!/bin/bash

protoc -I=./proto --java_out=./android/src ./proto/client.proto ./proto/message.proto ./proto/command.proto ./proto/settings.proto
protoc -I=./proto --cpp_out=./qt/lib/data ./proto/client.proto ./proto/message.proto ./proto/command.proto
