// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command.proto

package com.wlanadb.data;

public final class CommandProto {
  private CommandProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CommandOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional string pin = 1;
    boolean hasPin();
    String getPin();
    
    // optional string command = 2;
    boolean hasCommand();
    String getCommand();
    
    // repeated string params = 3;
    java.util.List<String> getParamsList();
    int getParamsCount();
    String getParams(int index);
    
    // optional uint64 length = 4;
    boolean hasLength();
    long getLength();
    
    // optional string checksum = 5;
    boolean hasChecksum();
    String getChecksum();
  }
  public static final class Command extends
      com.google.protobuf.GeneratedMessageLite
      implements CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(Builder builder) {
      super(builder);
    }
    private Command(boolean noInit) {}
    
    private static final Command defaultInstance;
    public static Command getDefaultInstance() {
      return defaultInstance;
    }
    
    public Command getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional string pin = 1;
    public static final int PIN_FIELD_NUMBER = 1;
    private java.lang.Object pin_;
    public boolean hasPin() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getPin() {
      java.lang.Object ref = pin_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pin_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPinBytes() {
      java.lang.Object ref = pin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string command = 2;
    public static final int COMMAND_FIELD_NUMBER = 2;
    private java.lang.Object command_;
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getCommand() {
      java.lang.Object ref = command_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          command_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string params = 3;
    public static final int PARAMS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList params_;
    public java.util.List<String>
        getParamsList() {
      return params_;
    }
    public int getParamsCount() {
      return params_.size();
    }
    public String getParams(int index) {
      return params_.get(index);
    }
    
    // optional uint64 length = 4;
    public static final int LENGTH_FIELD_NUMBER = 4;
    private long length_;
    public boolean hasLength() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getLength() {
      return length_;
    }
    
    // optional string checksum = 5;
    public static final int CHECKSUM_FIELD_NUMBER = 5;
    private java.lang.Object checksum_;
    public boolean hasChecksum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getChecksum() {
      java.lang.Object ref = checksum_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          checksum_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getChecksumBytes() {
      java.lang.Object ref = checksum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        checksum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      pin_ = "";
      command_ = "";
      params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      length_ = 0L;
      checksum_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPinBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCommandBytes());
      }
      for (int i = 0; i < params_.size(); i++) {
        output.writeBytes(3, params_.getByteString(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(4, length_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getChecksumBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPinBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCommandBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < params_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(params_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getParamsList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, length_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getChecksumBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.wlanadb.data.CommandProto.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wlanadb.data.CommandProto.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wlanadb.data.CommandProto.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wlanadb.data.CommandProto.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wlanadb.data.CommandProto.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wlanadb.data.CommandProto.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.wlanadb.data.CommandProto.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wlanadb.data.CommandProto.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wlanadb.data.CommandProto.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wlanadb.data.CommandProto.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wlanadb.data.CommandProto.Command prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.wlanadb.data.CommandProto.Command, Builder>
        implements com.wlanadb.data.CommandProto.CommandOrBuilder {
      // Construct using com.wlanadb.data.CommandProto.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        pin_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        length_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        checksum_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.wlanadb.data.CommandProto.Command getDefaultInstanceForType() {
        return com.wlanadb.data.CommandProto.Command.getDefaultInstance();
      }
      
      public com.wlanadb.data.CommandProto.Command build() {
        com.wlanadb.data.CommandProto.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.wlanadb.data.CommandProto.Command buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.wlanadb.data.CommandProto.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.wlanadb.data.CommandProto.Command buildPartial() {
        com.wlanadb.data.CommandProto.Command result = new com.wlanadb.data.CommandProto.Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pin_ = pin_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.command_ = command_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          params_ = new com.google.protobuf.UnmodifiableLazyStringList(
              params_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.params_ = params_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.length_ = length_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.checksum_ = checksum_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.wlanadb.data.CommandProto.Command other) {
        if (other == com.wlanadb.data.CommandProto.Command.getDefaultInstance()) return this;
        if (other.hasPin()) {
          setPin(other.getPin());
        }
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (!other.params_.isEmpty()) {
          if (params_.isEmpty()) {
            params_ = other.params_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureParamsIsMutable();
            params_.addAll(other.params_);
          }
          
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (other.hasChecksum()) {
          setChecksum(other.getChecksum());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              pin_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              command_ = input.readBytes();
              break;
            }
            case 26: {
              ensureParamsIsMutable();
              params_.add(input.readBytes());
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              length_ = input.readUInt64();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              checksum_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string pin = 1;
      private java.lang.Object pin_ = "";
      public boolean hasPin() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getPin() {
        java.lang.Object ref = pin_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pin_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPin(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pin_ = value;
        
        return this;
      }
      public Builder clearPin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pin_ = getDefaultInstance().getPin();
        
        return this;
      }
      void setPin(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        pin_ = value;
        
      }
      
      // optional string command = 2;
      private java.lang.Object command_ = "";
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getCommand() {
        java.lang.Object ref = command_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          command_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCommand(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        command_ = value;
        
        return this;
      }
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000002);
        command_ = getDefaultInstance().getCommand();
        
        return this;
      }
      void setCommand(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        command_ = value;
        
      }
      
      // repeated string params = 3;
      private com.google.protobuf.LazyStringList params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParamsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          params_ = new com.google.protobuf.LazyStringArrayList(params_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<String>
          getParamsList() {
        return java.util.Collections.unmodifiableList(params_);
      }
      public int getParamsCount() {
        return params_.size();
      }
      public String getParams(int index) {
        return params_.get(index);
      }
      public Builder setParams(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
        params_.set(index, value);
        
        return this;
      }
      public Builder addParams(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
        params_.add(value);
        
        return this;
      }
      public Builder addAllParams(
          java.lang.Iterable<String> values) {
        ensureParamsIsMutable();
        super.addAll(values, params_);
        
        return this;
      }
      public Builder clearParams() {
        params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        
        return this;
      }
      void addParams(com.google.protobuf.ByteString value) {
        ensureParamsIsMutable();
        params_.add(value);
        
      }
      
      // optional uint64 length = 4;
      private long length_ ;
      public boolean hasLength() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getLength() {
        return length_;
      }
      public Builder setLength(long value) {
        bitField0_ |= 0x00000008;
        length_ = value;
        
        return this;
      }
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000008);
        length_ = 0L;
        
        return this;
      }
      
      // optional string checksum = 5;
      private java.lang.Object checksum_ = "";
      public boolean hasChecksum() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getChecksum() {
        java.lang.Object ref = checksum_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          checksum_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setChecksum(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        checksum_ = value;
        
        return this;
      }
      public Builder clearChecksum() {
        bitField0_ = (bitField0_ & ~0x00000010);
        checksum_ = getDefaultInstance().getChecksum();
        
        return this;
      }
      void setChecksum(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        checksum_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:com.wlanadb.data.Command)
    }
    
    static {
      defaultInstance = new Command(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.wlanadb.data.Command)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
