// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.wlanadb.data;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .com.wlanadb.data.Message.Type type = 1;
    boolean hasType();
    com.wlanadb.data.MessageProto.Message.Type getType();
    
    // optional .com.wlanadb.data.Client client = 2;
    boolean hasClient();
    com.wlanadb.data.ClientProto.Client getClient();
  }
  public static final class Message extends
      com.google.protobuf.GeneratedMessageLite
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(Builder builder) {
      super(builder);
    }
    private Message(boolean noInit) {}
    
    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }
    
    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public enum Type
        implements com.google.protobuf.Internal.EnumLite {
      REQEST(0, 0),
      RESPONSE(1, 1),
      ;
      
      public static final int REQEST_VALUE = 0;
      public static final int RESPONSE_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 0: return REQEST;
          case 1: return RESPONSE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      private final int value;
      
      private Type(int index, int value) {
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.wlanadb.data.Message.Type)
    }
    
    private int bitField0_;
    // required .com.wlanadb.data.Message.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.wlanadb.data.MessageProto.Message.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.wlanadb.data.MessageProto.Message.Type getType() {
      return type_;
    }
    
    // optional .com.wlanadb.data.Client client = 2;
    public static final int CLIENT_FIELD_NUMBER = 2;
    private com.wlanadb.data.ClientProto.Client client_;
    public boolean hasClient() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.wlanadb.data.ClientProto.Client getClient() {
      return client_;
    }
    
    private void initFields() {
      type_ = com.wlanadb.data.MessageProto.Message.Type.REQEST;
      client_ = com.wlanadb.data.ClientProto.Client.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasClient()) {
        if (!getClient().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, client_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, client_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.wlanadb.data.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wlanadb.data.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wlanadb.data.MessageProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wlanadb.data.MessageProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wlanadb.data.MessageProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wlanadb.data.MessageProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.wlanadb.data.MessageProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wlanadb.data.MessageProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wlanadb.data.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wlanadb.data.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wlanadb.data.MessageProto.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.wlanadb.data.MessageProto.Message, Builder>
        implements com.wlanadb.data.MessageProto.MessageOrBuilder {
      // Construct using com.wlanadb.data.MessageProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = com.wlanadb.data.MessageProto.Message.Type.REQEST;
        bitField0_ = (bitField0_ & ~0x00000001);
        client_ = com.wlanadb.data.ClientProto.Client.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.wlanadb.data.MessageProto.Message getDefaultInstanceForType() {
        return com.wlanadb.data.MessageProto.Message.getDefaultInstance();
      }
      
      public com.wlanadb.data.MessageProto.Message build() {
        com.wlanadb.data.MessageProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.wlanadb.data.MessageProto.Message buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.wlanadb.data.MessageProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.wlanadb.data.MessageProto.Message buildPartial() {
        com.wlanadb.data.MessageProto.Message result = new com.wlanadb.data.MessageProto.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.client_ = client_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.wlanadb.data.MessageProto.Message other) {
        if (other == com.wlanadb.data.MessageProto.Message.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasClient()) {
          mergeClient(other.getClient());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasClient()) {
          if (!getClient().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.wlanadb.data.MessageProto.Message.Type value = com.wlanadb.data.MessageProto.Message.Type.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              com.wlanadb.data.ClientProto.Client.Builder subBuilder = com.wlanadb.data.ClientProto.Client.newBuilder();
              if (hasClient()) {
                subBuilder.mergeFrom(getClient());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setClient(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.wlanadb.data.Message.Type type = 1;
      private com.wlanadb.data.MessageProto.Message.Type type_ = com.wlanadb.data.MessageProto.Message.Type.REQEST;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.wlanadb.data.MessageProto.Message.Type getType() {
        return type_;
      }
      public Builder setType(com.wlanadb.data.MessageProto.Message.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.wlanadb.data.MessageProto.Message.Type.REQEST;
        
        return this;
      }
      
      // optional .com.wlanadb.data.Client client = 2;
      private com.wlanadb.data.ClientProto.Client client_ = com.wlanadb.data.ClientProto.Client.getDefaultInstance();
      public boolean hasClient() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.wlanadb.data.ClientProto.Client getClient() {
        return client_;
      }
      public Builder setClient(com.wlanadb.data.ClientProto.Client value) {
        if (value == null) {
          throw new NullPointerException();
        }
        client_ = value;
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setClient(
          com.wlanadb.data.ClientProto.Client.Builder builderForValue) {
        client_ = builderForValue.build();
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeClient(com.wlanadb.data.ClientProto.Client value) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            client_ != com.wlanadb.data.ClientProto.Client.getDefaultInstance()) {
          client_ =
            com.wlanadb.data.ClientProto.Client.newBuilder(client_).mergeFrom(value).buildPartial();
        } else {
          client_ = value;
        }
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearClient() {
        client_ = com.wlanadb.data.ClientProto.Client.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.wlanadb.data.Message)
    }
    
    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.wlanadb.data.Message)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
