// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: settings.proto

package com.wlanadb.data;

public final class SettingsProto {
    private SettingsProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public interface SettingsOrBuilder
            extends com.google.protobuf.MessageLiteOrBuilder {

        // optional int32 version = 1;
        boolean hasVersion();

        int getVersion();

        // optional .com.wlanadb.data.Client client = 2;
        boolean hasClient();

        ClientProto.Client getClient();

        // optional string pin = 3;
        boolean hasPin();

        String getPin();

        // optional bool trusted_hotspots_enabled = 4 [default = false];
        boolean hasTrustedHotspotsEnabled();

        boolean getTrustedHotspotsEnabled();

        // repeated string trusted_hotspots = 5;
        java.util.List<String> getTrustedHotspotsList();

        int getTrustedHotspotsCount();

        String getTrustedHotspots(int index);

        // optional bool ask_to_install = 6 [default = true];
        boolean hasAskToInstall();

        boolean getAskToInstall();

        // optional bool wifi_lock_enabled = 7 [default = false];
        boolean hasWifiLockEnabled();

        boolean getWifiLockEnabled();
    }

    public static final class Settings extends
            com.google.protobuf.GeneratedMessageLite
            implements SettingsOrBuilder {
        // Use Settings.newBuilder() to construct.
        private Settings(Builder builder) {
            super(builder);
        }

        private Settings(boolean noInit) {
        }

        private static final Settings defaultInstance;

        public static Settings getDefaultInstance() {
            return defaultInstance;
        }

        public Settings getDefaultInstanceForType() {
            return defaultInstance;
        }

        private int bitField0_;
        // optional int32 version = 1;
        public static final int VERSION_FIELD_NUMBER = 1;
        private int version_;

        public boolean hasVersion() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public int getVersion() {
            return version_;
        }

        // optional .com.wlanadb.data.Client client = 2;
        public static final int CLIENT_FIELD_NUMBER = 2;
        private ClientProto.Client client_;

        public boolean hasClient() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public ClientProto.Client getClient() {
            return client_;
        }

        // optional string pin = 3;
        public static final int PIN_FIELD_NUMBER = 3;
        private Object pin_;

        public boolean hasPin() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        public String getPin() {
            Object ref = pin_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    pin_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getPinBytes() {
            Object ref = pin_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                pin_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional bool trusted_hotspots_enabled = 4 [default = false];
        public static final int TRUSTED_HOTSPOTS_ENABLED_FIELD_NUMBER = 4;
        private boolean trustedHotspotsEnabled_;

        public boolean hasTrustedHotspotsEnabled() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        public boolean getTrustedHotspotsEnabled() {
            return trustedHotspotsEnabled_;
        }

        // repeated string trusted_hotspots = 5;
        public static final int TRUSTED_HOTSPOTS_FIELD_NUMBER = 5;
        private com.google.protobuf.LazyStringList trustedHotspots_;

        public java.util.List<String>
        getTrustedHotspotsList() {
            return trustedHotspots_;
        }

        public int getTrustedHotspotsCount() {
            return trustedHotspots_.size();
        }

        public String getTrustedHotspots(int index) {
            return trustedHotspots_.get(index);
        }

        // optional bool ask_to_install = 6 [default = true];
        public static final int ASK_TO_INSTALL_FIELD_NUMBER = 6;
        private boolean askToInstall_;

        public boolean hasAskToInstall() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        public boolean getAskToInstall() {
            return askToInstall_;
        }

        // optional bool wifi_lock_enabled = 7 [default = false];
        public static final int WIFI_LOCK_ENABLED_FIELD_NUMBER = 7;
        private boolean wifiLockEnabled_;

        public boolean hasWifiLockEnabled() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }

        public boolean getWifiLockEnabled() {
            return wifiLockEnabled_;
        }

        private void initFields() {
            version_ = 0;
            client_ = ClientProto.Client.getDefaultInstance();
            pin_ = "";
            trustedHotspotsEnabled_ = false;
            trustedHotspots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            askToInstall_ = true;
            wifiLockEnabled_ = false;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (hasClient()) {
                if (!getClient().isInitialized()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, version_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeMessage(2, client_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getPinBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeBool(4, trustedHotspotsEnabled_);
            }
            for (int i = 0; i < trustedHotspots_.size(); i++) {
                output.writeBytes(5, trustedHotspots_.getByteString(i));
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeBool(6, askToInstall_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                output.writeBool(7, wifiLockEnabled_);
            }
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, version_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, client_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, getPinBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(4, trustedHotspotsEnabled_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < trustedHotspots_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeBytesSizeNoTag(trustedHotspots_.getByteString(i));
                }
                size += dataSize;
                size += 1 * getTrustedHotspotsList().size();
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(6, askToInstall_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(7, wifiLockEnabled_);
            }
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static Settings parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static Settings parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static Settings parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static Settings parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static Settings parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static Settings parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Settings parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static Settings parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static Settings parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static Settings parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(Settings prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        Settings, Builder>
                implements SettingsOrBuilder {
            // Construct using com.wlanadb.data.SettingsProto.Settings.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                version_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                client_ = ClientProto.Client.getDefaultInstance();
                bitField0_ = (bitField0_ & ~0x00000002);
                pin_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                trustedHotspotsEnabled_ = false;
                bitField0_ = (bitField0_ & ~0x00000008);
                trustedHotspots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000010);
                askToInstall_ = true;
                bitField0_ = (bitField0_ & ~0x00000020);
                wifiLockEnabled_ = false;
                bitField0_ = (bitField0_ & ~0x00000040);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public Settings getDefaultInstanceForType() {
                return Settings.getDefaultInstance();
            }

            public Settings build() {
                Settings result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private Settings buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Settings result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public Settings buildPartial() {
                Settings result = new Settings(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.version_ = version_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.client_ = client_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.pin_ = pin_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.trustedHotspotsEnabled_ = trustedHotspotsEnabled_;
                if (((bitField0_ & 0x00000010) == 0x00000010)) {
                    trustedHotspots_ = new com.google.protobuf.UnmodifiableLazyStringList(
                            trustedHotspots_);
                    bitField0_ = (bitField0_ & ~0x00000010);
                }
                result.trustedHotspots_ = trustedHotspots_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.askToInstall_ = askToInstall_;
                if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.wifiLockEnabled_ = wifiLockEnabled_;
                result.bitField0_ = to_bitField0_;
                return result;
            }

            public Builder mergeFrom(Settings other) {
                if (other == Settings.getDefaultInstance()) return this;
                if (other.hasVersion()) {
                    setVersion(other.getVersion());
                }
                if (other.hasClient()) {
                    mergeClient(other.getClient());
                }
                if (other.hasPin()) {
                    setPin(other.getPin());
                }
                if (other.hasTrustedHotspotsEnabled()) {
                    setTrustedHotspotsEnabled(other.getTrustedHotspotsEnabled());
                }
                if (!other.trustedHotspots_.isEmpty()) {
                    if (trustedHotspots_.isEmpty()) {
                        trustedHotspots_ = other.trustedHotspots_;
                        bitField0_ = (bitField0_ & ~0x00000010);
                    } else {
                        ensureTrustedHotspotsIsMutable();
                        trustedHotspots_.addAll(other.trustedHotspots_);
                    }

                }
                if (other.hasAskToInstall()) {
                    setAskToInstall(other.getAskToInstall());
                }
                if (other.hasWifiLockEnabled()) {
                    setWifiLockEnabled(other.getWifiLockEnabled());
                }
                return this;
            }

            public final boolean isInitialized() {
                if (hasClient()) {
                    if (!getClient().isInitialized()) {

                        return false;
                    }
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:

                            return this;
                        default: {
                            if (!parseUnknownField(input, extensionRegistry, tag)) {

                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            version_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            ClientProto.Client.Builder subBuilder = ClientProto.Client.newBuilder();
                            if (hasClient()) {
                                subBuilder.mergeFrom(getClient());
                            }
                            input.readMessage(subBuilder, extensionRegistry);
                            setClient(subBuilder.buildPartial());
                            break;
                        }
                        case 26: {
                            bitField0_ |= 0x00000004;
                            pin_ = input.readBytes();
                            break;
                        }
                        case 32: {
                            bitField0_ |= 0x00000008;
                            trustedHotspotsEnabled_ = input.readBool();
                            break;
                        }
                        case 42: {
                            ensureTrustedHotspotsIsMutable();
                            trustedHotspots_.add(input.readBytes());
                            break;
                        }
                        case 48: {
                            bitField0_ |= 0x00000020;
                            askToInstall_ = input.readBool();
                            break;
                        }
                        case 56: {
                            bitField0_ |= 0x00000040;
                            wifiLockEnabled_ = input.readBool();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // optional int32 version = 1;
            private int version_;

            public boolean hasVersion() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getVersion() {
                return version_;
            }

            public Builder setVersion(int value) {
                bitField0_ |= 0x00000001;
                version_ = value;

                return this;
            }

            public Builder clearVersion() {
                bitField0_ = (bitField0_ & ~0x00000001);
                version_ = 0;

                return this;
            }

            // optional .com.wlanadb.data.Client client = 2;
            private ClientProto.Client client_ = ClientProto.Client.getDefaultInstance();

            public boolean hasClient() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public ClientProto.Client getClient() {
                return client_;
            }

            public Builder setClient(ClientProto.Client value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                client_ = value;

                bitField0_ |= 0x00000002;
                return this;
            }

            public Builder setClient(
                    ClientProto.Client.Builder builderForValue) {
                client_ = builderForValue.build();

                bitField0_ |= 0x00000002;
                return this;
            }

            public Builder mergeClient(ClientProto.Client value) {
                if (((bitField0_ & 0x00000002) == 0x00000002) &&
                        client_ != ClientProto.Client.getDefaultInstance()) {
                    client_ =
                            ClientProto.Client.newBuilder(client_).mergeFrom(value).buildPartial();
                } else {
                    client_ = value;
                }

                bitField0_ |= 0x00000002;
                return this;
            }

            public Builder clearClient() {
                client_ = ClientProto.Client.getDefaultInstance();

                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            // optional string pin = 3;
            private Object pin_ = "";

            public boolean hasPin() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            public String getPin() {
                Object ref = pin_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    pin_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setPin(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                pin_ = value;

                return this;
            }

            public Builder clearPin() {
                bitField0_ = (bitField0_ & ~0x00000004);
                pin_ = getDefaultInstance().getPin();

                return this;
            }

            void setPin(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000004;
                pin_ = value;

            }

            // optional bool trusted_hotspots_enabled = 4 [default = false];
            private boolean trustedHotspotsEnabled_;

            public boolean hasTrustedHotspotsEnabled() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            public boolean getTrustedHotspotsEnabled() {
                return trustedHotspotsEnabled_;
            }

            public Builder setTrustedHotspotsEnabled(boolean value) {
                bitField0_ |= 0x00000008;
                trustedHotspotsEnabled_ = value;

                return this;
            }

            public Builder clearTrustedHotspotsEnabled() {
                bitField0_ = (bitField0_ & ~0x00000008);
                trustedHotspotsEnabled_ = false;

                return this;
            }

            // repeated string trusted_hotspots = 5;
            private com.google.protobuf.LazyStringList trustedHotspots_ = com.google.protobuf.LazyStringArrayList.EMPTY;

            private void ensureTrustedHotspotsIsMutable() {
                if (!((bitField0_ & 0x00000010) == 0x00000010)) {
                    trustedHotspots_ = new com.google.protobuf.LazyStringArrayList(trustedHotspots_);
                    bitField0_ |= 0x00000010;
                }
            }

            public java.util.List<String>
            getTrustedHotspotsList() {
                return java.util.Collections.unmodifiableList(trustedHotspots_);
            }

            public int getTrustedHotspotsCount() {
                return trustedHotspots_.size();
            }

            public String getTrustedHotspots(int index) {
                return trustedHotspots_.get(index);
            }

            public Builder setTrustedHotspots(
                    int index, String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureTrustedHotspotsIsMutable();
                trustedHotspots_.set(index, value);

                return this;
            }

            public Builder addTrustedHotspots(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureTrustedHotspotsIsMutable();
                trustedHotspots_.add(value);

                return this;
            }

            public Builder addAllTrustedHotspots(
                    Iterable<String> values) {
                ensureTrustedHotspotsIsMutable();
                super.addAll(values, trustedHotspots_);

                return this;
            }

            public Builder clearTrustedHotspots() {
                trustedHotspots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000010);

                return this;
            }

            void addTrustedHotspots(com.google.protobuf.ByteString value) {
                ensureTrustedHotspotsIsMutable();
                trustedHotspots_.add(value);

            }

            // optional bool ask_to_install = 6 [default = true];
            private boolean askToInstall_ = true;

            public boolean hasAskToInstall() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }

            public boolean getAskToInstall() {
                return askToInstall_;
            }

            public Builder setAskToInstall(boolean value) {
                bitField0_ |= 0x00000020;
                askToInstall_ = value;

                return this;
            }

            public Builder clearAskToInstall() {
                bitField0_ = (bitField0_ & ~0x00000020);
                askToInstall_ = true;

                return this;
            }

            // optional bool wifi_lock_enabled = 7 [default = false];
            private boolean wifiLockEnabled_;

            public boolean hasWifiLockEnabled() {
                return ((bitField0_ & 0x00000040) == 0x00000040);
            }

            public boolean getWifiLockEnabled() {
                return wifiLockEnabled_;
            }

            public Builder setWifiLockEnabled(boolean value) {
                bitField0_ |= 0x00000040;
                wifiLockEnabled_ = value;

                return this;
            }

            public Builder clearWifiLockEnabled() {
                bitField0_ = (bitField0_ & ~0x00000040);
                wifiLockEnabled_ = false;

                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.wlanadb.data.Settings)
        }

        static {
            defaultInstance = new Settings(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.wlanadb.data.Settings)
    }


    static {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
