// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.wlancat.data;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .com.wlancat.data.Message.Type type = 1;
    boolean hasType();
    com.wlancat.data.MessageProto.Message.Type getType();
    
    // optional .com.wlancat.data.Client client = 2;
    boolean hasClient();
    com.wlancat.data.ClientProto.Client getClient();
    com.wlancat.data.ClientProto.ClientOrBuilder getClientOrBuilder();
  }
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(Builder builder) {
      super(builder);
    }
    private Message(boolean noInit) {}
    
    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }
    
    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wlancat.data.MessageProto.internal_static_com_wlancat_data_Message_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wlancat.data.MessageProto.internal_static_com_wlancat_data_Message_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      REQEST(0, 0),
      RESPONSE(1, 1),
      ;
      
      public static final int REQEST_VALUE = 0;
      public static final int RESPONSE_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 0: return REQEST;
          case 1: return RESPONSE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.wlancat.data.MessageProto.Message.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        REQEST, RESPONSE, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.wlancat.data.Message.Type)
    }
    
    private int bitField0_;
    // required .com.wlancat.data.Message.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.wlancat.data.MessageProto.Message.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.wlancat.data.MessageProto.Message.Type getType() {
      return type_;
    }
    
    // optional .com.wlancat.data.Client client = 2;
    public static final int CLIENT_FIELD_NUMBER = 2;
    private com.wlancat.data.ClientProto.Client client_;
    public boolean hasClient() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.wlancat.data.ClientProto.Client getClient() {
      return client_;
    }
    public com.wlancat.data.ClientProto.ClientOrBuilder getClientOrBuilder() {
      return client_;
    }
    
    private void initFields() {
      type_ = com.wlancat.data.MessageProto.Message.Type.REQEST;
      client_ = com.wlancat.data.ClientProto.Client.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasClient()) {
        if (!getClient().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, client_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, client_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.wlancat.data.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wlancat.data.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wlancat.data.MessageProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.wlancat.data.MessageProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.wlancat.data.MessageProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wlancat.data.MessageProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.wlancat.data.MessageProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wlancat.data.MessageProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.wlancat.data.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.wlancat.data.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wlancat.data.MessageProto.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wlancat.data.MessageProto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wlancat.data.MessageProto.internal_static_com_wlancat_data_Message_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wlancat.data.MessageProto.internal_static_com_wlancat_data_Message_fieldAccessorTable;
      }
      
      // Construct using com.wlancat.data.MessageProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getClientFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = com.wlancat.data.MessageProto.Message.Type.REQEST;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (clientBuilder_ == null) {
          client_ = com.wlancat.data.ClientProto.Client.getDefaultInstance();
        } else {
          clientBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wlancat.data.MessageProto.Message.getDescriptor();
      }
      
      public com.wlancat.data.MessageProto.Message getDefaultInstanceForType() {
        return com.wlancat.data.MessageProto.Message.getDefaultInstance();
      }
      
      public com.wlancat.data.MessageProto.Message build() {
        com.wlancat.data.MessageProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.wlancat.data.MessageProto.Message buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.wlancat.data.MessageProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.wlancat.data.MessageProto.Message buildPartial() {
        com.wlancat.data.MessageProto.Message result = new com.wlancat.data.MessageProto.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (clientBuilder_ == null) {
          result.client_ = client_;
        } else {
          result.client_ = clientBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wlancat.data.MessageProto.Message) {
          return mergeFrom((com.wlancat.data.MessageProto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.wlancat.data.MessageProto.Message other) {
        if (other == com.wlancat.data.MessageProto.Message.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasClient()) {
          mergeClient(other.getClient());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasClient()) {
          if (!getClient().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.wlancat.data.MessageProto.Message.Type value = com.wlancat.data.MessageProto.Message.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              com.wlancat.data.ClientProto.Client.Builder subBuilder = com.wlancat.data.ClientProto.Client.newBuilder();
              if (hasClient()) {
                subBuilder.mergeFrom(getClient());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setClient(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.wlancat.data.Message.Type type = 1;
      private com.wlancat.data.MessageProto.Message.Type type_ = com.wlancat.data.MessageProto.Message.Type.REQEST;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.wlancat.data.MessageProto.Message.Type getType() {
        return type_;
      }
      public Builder setType(com.wlancat.data.MessageProto.Message.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.wlancat.data.MessageProto.Message.Type.REQEST;
        onChanged();
        return this;
      }
      
      // optional .com.wlancat.data.Client client = 2;
      private com.wlancat.data.ClientProto.Client client_ = com.wlancat.data.ClientProto.Client.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.wlancat.data.ClientProto.Client, com.wlancat.data.ClientProto.Client.Builder, com.wlancat.data.ClientProto.ClientOrBuilder> clientBuilder_;
      public boolean hasClient() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.wlancat.data.ClientProto.Client getClient() {
        if (clientBuilder_ == null) {
          return client_;
        } else {
          return clientBuilder_.getMessage();
        }
      }
      public Builder setClient(com.wlancat.data.ClientProto.Client value) {
        if (clientBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          client_ = value;
          onChanged();
        } else {
          clientBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setClient(
          com.wlancat.data.ClientProto.Client.Builder builderForValue) {
        if (clientBuilder_ == null) {
          client_ = builderForValue.build();
          onChanged();
        } else {
          clientBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeClient(com.wlancat.data.ClientProto.Client value) {
        if (clientBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              client_ != com.wlancat.data.ClientProto.Client.getDefaultInstance()) {
            client_ =
              com.wlancat.data.ClientProto.Client.newBuilder(client_).mergeFrom(value).buildPartial();
          } else {
            client_ = value;
          }
          onChanged();
        } else {
          clientBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearClient() {
        if (clientBuilder_ == null) {
          client_ = com.wlancat.data.ClientProto.Client.getDefaultInstance();
          onChanged();
        } else {
          clientBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.wlancat.data.ClientProto.Client.Builder getClientBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getClientFieldBuilder().getBuilder();
      }
      public com.wlancat.data.ClientProto.ClientOrBuilder getClientOrBuilder() {
        if (clientBuilder_ != null) {
          return clientBuilder_.getMessageOrBuilder();
        } else {
          return client_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.wlancat.data.ClientProto.Client, com.wlancat.data.ClientProto.Client.Builder, com.wlancat.data.ClientProto.ClientOrBuilder> 
          getClientFieldBuilder() {
        if (clientBuilder_ == null) {
          clientBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.wlancat.data.ClientProto.Client, com.wlancat.data.ClientProto.Client.Builder, com.wlancat.data.ClientProto.ClientOrBuilder>(
                  client_,
                  getParentForChildren(),
                  isClean());
          client_ = null;
        }
        return clientBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.wlancat.data.Message)
    }
    
    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.wlancat.data.Message)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wlancat_data_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wlancat_data_Message_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\020com.wlancat.data\032\014clien" +
      "t.proto\"\203\001\n\007Message\022,\n\004type\030\001 \002(\0162\036.com." +
      "wlancat.data.Message.Type\022(\n\006client\030\002 \001(" +
      "\0132\030.com.wlancat.data.Client\" \n\004Type\022\n\n\006R" +
      "EQEST\020\000\022\014\n\010RESPONSE\020\001B \n\020com.wlancat.dat" +
      "aB\014MessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_wlancat_data_Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_wlancat_data_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wlancat_data_Message_descriptor,
              new java.lang.String[] { "Type", "Client", },
              com.wlancat.data.MessageProto.Message.class,
              com.wlancat.data.MessageProto.Message.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wlancat.data.ClientProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
